trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Pipeline is running..."
  displayName: 'Run a one-line script'

- task: CopyFiles@2
  inputs:
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'